[package]
name = "numa-infer"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[features]
dump-switches = []

[dependencies]
image.workspace = true
log.workspace = true
ndarray.workspace = true
ort.workspace = true

[target.'cfg(target_os = "ios")'.dependencies]
ort = { workspace = true, features = ["coreml"] }

[dev-dependencies]
numa-cull = { path = "../numa-cull" }
numa-io = { path = "../numa-io" }
numa-render = { path = "../numa-render" }
